### PR TITLE
proper import path

### PR DESCRIPTION
**Pull request by slawosz**

### CODE REVIEW

**Comment by josharian** [comment]
Thanks! However, this should actually be golang.org/x/tools/...

**Comment by slawosz** [comment]
Yes, looks like I opened it too fast. Let me investigate.

**Comment by jmoiron** [comment]
Didn't see this.  I created a PR with the proper path.  Feel free to close one/both and fix it, it's a tiny change.

**Comment by josharian** [comment]
Covered by #9. Thanks.

**Pull request closed without merging**
